name: Main

on: 
  push:
    paths:
    - '**.ts'
    - '.github/workflows/build.yml'
    - 'package.json'
    - 'tsconfig.json'
    - 'manifest.json'
    - 'pack_icon.png'
    - 'tsconfig.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Build
        run: npm i && tsc -d --target es2021 && rm -rf node_modules && find ./scripts -name "*.ts" -delete && zip -r gohome.mcpack *
      - name: Get current date and time
        env: 
          TZ: "Asia/Tokyo" # タイムゾーンを指定
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.date }}
          files: |
            gohome.mcpack
